### ISSUE TITLE
Is it possible to save the 3D mesh?

### ISSUE THREAD

**Issue by saihv** [midgen/uesvon#11]
Either as an octomap (considering it's already an octree) or some sort of a 3D mesh format. Does the current internal representation match a standard one?

**Comment by midgen** [comment]
The data structure is detailed in this article (which is free now). Chapter 21.3. It'll be pretty straightforward to export the data to whatever format you need, I already convert it to render the visual logger representation.

http://www.gameaipro.com/GameAIPro3/GameAIPro3_Chapter21_3D_Flight_Navigation_Using_Sparse_Voxel_Octrees.pdf

**Comment by saihv** [comment]
Thanks for the reference. Closing
