### ISSUE TITLE
Engine Version?

### ISSUE THREAD

**Issue by HeadClot** [midgen/uesvon#2]
Hey @midgen - What engine version is this meant to be used with?

And would it be possible to put that engine version in the Read Me.?

**Comment by midgen** [comment]
It's built for 4.19 at the moment (the version it started on). I usually wait until a .X release and then branch the old version off, before updating master to latest.

I'll probably update to 4.20 next week. Feel free to add a pull request to amend the readme!
________________________________

**Comment by midgen** [comment]
Master is now updated to 4.20. I've created a 4.19 branch.
