### ISSUE TITLE
Make a simple scenario

### ISSUE THREAD

**Issue by sihnatse** [midgen/uesvon#21]
Suggestion: make a simple scenario and publish it step-by-step: for example, make SVON volume - locate pawn - set destination - find navigation path and show it.

Because of the lack of simple scenario (or test case), debugging C++ code is necessary - no path can be build between any of two locations. The path generation is called from BP `FindPathImmediate` node and error says that "pawn is not inside SVON volume or nav data has not been generated". This error message is not true because, in Editor, it is seen exactly opposite - pawn is inside generated mesh. 

![IMG_6788](https://user-images.githubusercontent.com/34723840/134898668-1cb974de-5f8e-4ab2-99f9-6441a1a9ca6b.jpg)

**Comment by midgen** [comment]
The CashDemo repo on my profile has a demo project, with a simple scene and example AI driven pawn that attempts to follow the player.
