### ISSUE TITLE
Is it sparse voxel octree?

### ISSUE THREAD

**Issue by sihnatse** [midgen/uesvon#22]
There is a video on YouTube showing the sparse voxel octree navigation mesh. However, this plugin can only generate regular grid. Why?

This issue should be clearly stated in ReadMe and in Wiki.

**Comment by midgen** [comment]
The plugin is definitely built using a sparse voxel octree, the code in this repo is what was used to generate the video.

**Comment by sihnatse** [comment]
Aha, it does generate sparse mesh. In above scene, water is probably treated as obstacle. If you continue to work on this plugin, you might consider to add exclusion actors into meshing routine.

![IMG_6799](https://user-images.githubusercontent.com/34723840/136048099-78e5370b-5eac-4c0e-929c-8302c8c851cf.jpg)

Thanks for quick answering!
