### ISSUE TITLE
License

### ISSUE THREAD

**Issue by quarxpl** [midgen/uesvon#9]
Could you please clarify what is the license for this code?

As far as I understand, code without any license is "all rights reserved" and cannot be used for anything other than fun.

Thanks!

**Comment by Atulin** [comment]
[Correct](https://choosealicense.com/no-permission/). The lack of license makes it legally unusable.

**Comment by midgen** [comment]
Sorry, added now 8523e4bc1557a5f062dc7fa467be67ebbe652d8a
